# Generated by Django 6.0 on 2025-12-16 09:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fields'], name='product_fields_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.Func(models.F('fields'), models.Value('price'), function='jsonb_extract_path_text', output_field=models.TextField()), name='product_price_idx'),
        ),
    ]
